# Generated by Django 5.0.7 on 2024-07-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Artist',
        ),
    ]
